"use client"
import { Inter } from "next/font/google";
import "./globals.css";
// import Navigationbar from "./components/Navigationbar";
import { ReduxProviders } from "./components/ReduxAuthProviders";
import * as React from 'react';
import "./globals.css"
import Appbar from "./components/Appbar";
import Sidebar from "./components/Sidebar";
import { Box, CssBaseline, Toolbar } from "@mui/material";
const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    // <Provider store={store}>
    <html>
      <body>
        <ReduxProviders>
          <Box sx={{ display: 'flex' }}>
            <CssBaseline />
            <Appbar />
            <Sidebar />
          </Box>
          <Box component="main" sx={{ overflowX: 'scroll' }}>
            <Toolbar />
            <div className="mt-10 ml-20 mr-20 w-full h-full snap-x">{children}</div>
          </Box>

        </ReduxProviders>
      </body>
    </html >

    // </Provider> 

  );
}
